version: '3.9'

services:
  nginx:
    container_name: nginx-laravel
    #image: nginx:1.21.1-alpine
    build:
      context: ./docker/nginx
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ./www:/var/www/laravel
      - ./nginx-conf:/etc/nginx/templates
    environment:
      VIRTUAL_HOST: ${GLOBAL_DOMAIN}
      GLOBAL_DOMAIN: ${GLOBAL_DOMAIN}
      SERVER_PORT: ${SERVER_PORT}
      MAX_BUF_SIZE: ${MAX_BUF_SIZE}
      MAX_BODY_SIZE: ${MAX_BODY_SIZE}
      #ROOT_DIR: ${ROOT_DIR}
      #INDEX_DIR: ${INDEX_DIR}
    networks:
      - laravel
    depends_on:
      - php-laravel
    restart: always

  php-fpm:
    container_name: php-laravel
    #image: php:7.4-fpm
    build:
      context: ./docker/php
    ports:
      - ${PHP_PORT}:80
    volumes:
      - ./www:/var/www/laravel
      - ./php-conf/def-conf.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    depends_on:
      - mysql-laravel
    networks:
      - laravel
    restart: always

  #composer:
  #  container_name: composer
  #  image: composer:latest
  #  build:
  #    context: ./docker/composer
  #  working_dir: /composer
  #  volumes:
  #    - ./www/composer.json:/composer/composer.json
  #    - ./www/local:/composer/local
  #  restart: on-failure

  mysql:
    container_name: mysql-laravel
    #mage: mysql:5.7-centos
    ports:
      - '3306:3306'
    build:
      context: ./docker/mysql
    command: mysqld --innodb_strict_mode=0
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    #  - './docker/mysql/conf:/etc/mysql/conf.d'
    networks:
      - laravel
    restart: always

  memcached:
    container_name: memcached-laravel
    image: memcached:latest
    ports:
      - '${MEMCACHED_PORT}:80'
    depends_on:
      - php-laravel
    networks:
      - laravel
    restart: on-failure

  phpmyadmin:
    container_name: phpmyadmin-laravel
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      PMA_HOST: mysql-laravel
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-laravel
    networks:
      - laravel
    restart: always

  node:
    container_name: node-laravel
    build:
      context: ./docker/node
    ports:
      - ${NODE_PORT}:80


networks:
  laravel:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24

volumes:
  mysql:
    driver: local