version: '3.9'

services:
  nginx:
    container_name: nginx
    #image: nginx:1.21.1-alpine
    build:
      context: ./docker/nginx
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ./www:/var/www/laravel
      - ./nginx-conf:/etc/nginx/templates
    environment:
      VIRTUAL_HOST: ${GLOBAL_DOMAIN}
      GLOBAL_DOMAIN: ${GLOBAL_DOMAIN}
      SERVER_PORT: ${SERVER_PORT}
      MAX_BUF_SIZE: ${MAX_BUF_SIZE}
      MAX_BODY_SIZE: ${MAX_BODY_SIZE}
      #ROOT_DIR: ${ROOT_DIR}
      #INDEX_DIR: ${INDEX_DIR}
    networks:
      - bitrix
    depends_on:
      - php
    restart: always

  php-fpm:
    container_name: php
    #image: php:7.4-fpm
    build:
      context: ./docker/php
    ports:
      - ${PHP_PORT}:8000
    volumes:
      - ./www:/var/www/laravel
      - ./php-conf/def-conf.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    networks:
      - bitrix
    restart: always

  #composer:
  #  container_name: composer
  #  image: composer:latest
  #  build:
  #    context: ./docker/composer
  #  working_dir: /composer
  #  volumes:
  #    - ./www/composer.json:/composer/composer.json
  #    - ./www/local:/composer/local
  #  restart: on-failure

  mysql:
    container_name: mysql
    #mage: mysql:5.7-centos
    ports:
      - '${MYSQL_PORT}:8000'
    build:
      context: ./docker/mysql
    command: mysqld --innodb_strict_mode=0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - './mysql:/var/lib/mysql'
    #  - './docker/mysql/conf:/etc/mysql/conf.d'
    networks:
      - bitrix
    restart: always

  memcached:
    image: memcached:latest
    ports:
      - '${MEMCACHED_PORT}:80'
    networks:
      - bitrix
    depends_on:
      - php
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - bitrix
    restart: always

   #npm:
   #  container_name: npm
   #  build:
   #    context: ./docker/npm
   #  ports:
   #    - 48:80
   #  command:
   #    - npm run watch
   #  networks:
   #    - bitrix


networks:
  bitrix:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24