FROM nginx:1.21.1-alpine

RUN apk add bash mc

WORKDIR /var/www/laravel

#docker exec -u 0 nginx-kamo chown -R root:root /var/www/laravel/bitrix/cache
#docker exec -u 0 nginx-kamo chown -R root:root /var/www/laravel/bitrix/managed_cache